### ISSUE TITLE
Better transformation for Ch3 Q9-(f)

### ISSUE THREAD

**Issue by iamzjk** [asadoughi/stat-learning#43]
log transform mpg, produced better R-squared and residual diagnostics

here is the R code and output

> lm.fit2<-lm(log(mpg)~cylinders+displacement+horsepower+weight+sqrt(acceleration)+year+origin,data=Auto)
> summary(lm.fit2)
>par(mfrow=c(2,2)) 
>plot(lm.fit2)
> plot(predict(lm.fit2),rstudent(lm.fit2))

Call:
lm(formula = log(mpg) ~ cylinders + displacement + horsepower + 
    weight + sqrt(acceleration) + year + origin, data = Auto)

Residuals:
     Min       1Q   Median       3Q 
-0.41288 -0.06546  0.00002  0.06837 
     Max 
 0.34063 

Coefficients:
                     Estimate
(Intercept)         1.829e+00
cylinders          -2.806e-02
displacement        6.171e-04
horsepower         -1.615e-03
weight             -2.497e-04
sqrt(acceleration) -2.344e-02
year                2.952e-02
origin              4.068e-02
                   Std. Error t value
(Intercept)         1.986e-01   9.210
cylinders           1.156e-02  -2.428
displacement        2.699e-04   2.287
horsepower          5.008e-04  -3.225
weight              2.373e-05 -10.520
sqrt(acceleration)  2.896e-02  -0.810
year                1.823e-03  16.193
origin              9.948e-03   4.090
                   Pr(>|t|)    
(Intercept)         < 2e-16 ***
cylinders           0.01562 *  
displacement        0.02276 *  
horsepower          0.00137 ** 
weight              < 2e-16 ***
sqrt(acceleration)  0.41865    
year                < 2e-16 ***
origin             5.26e-05 ***

Signif. codes:  
  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05
  ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.119 on 384 degrees of freedom
Multiple R-squared:  0.8797,	Adjusted R-squared:  0.8775 
F-statistic:   401 on 7 and 384 DF,  p-value: < 2.2e-16

**Comment by asadoughi** [comment]
Hi, @iamzjk. Thank you for your submission! I haven't looked at it yet. I'll be sure to look at it with in the next week. In the meantime, if you are able to submit a pull request with the exact changes (Rmarkdown and HTML files) that would make my life easier. Thanks, again!

**Comment by iamzjk** [comment]
Hi Amir,

Thank you for your attention.
I never did the pull request on GitHub before. But I will try.

Jingkun

**Comment by asadoughi** [comment]
Closing this issue since #44 was merged.
